- name: Wait for all hosts to complete
  hosts: web001
  become: yes
  become_method: sudo
  become_user: root
  tasks: 
    - name: Wait unitil web002 is ready
      wait_for:
        path: /tmp/web002
      delegate_to: ansible.rhlab.ch
      remote_user: azureadm

#- name: Create user defined databases
#  mysql_db:
#    name: "{{ item.name }}"
#    login_user: root
#    login_password: "{{ mariadb_root_password }}"
#    state: present
#  with_items: "{{ mariadb_databases }}"
#  register: db_creation
#  tags: mariadb

- name: Install MariaDB 
  hosts: web001
  become: true
  vars:
    mariadb_bind_address: '0.0.0.0'
    mariadb_root_password: '&othErEek97FrewlAyd?'
    mariadb_databases:
      - name: wordpress_db
    mariadb_users:
      - name: wordpress_usr
        password: ywIapecJalg6
        priv: wordpress_db.*:ALL
        host: '10.1.1.%'
  roles:
    - bertvv.mariadb

